config/routes.rb
Rails.application.routes.draw do
  get 'doses/new'
  get 'doses/index'
  delete "cocktails/:id", to: "cocktails#destroy", as: :destroy
  delete "doses/:id", to: "doses#destroy", as: :dose_destroy
  resources :cocktails do
    resources :doses
  end
  resources :doses, only: [:edit, :new, :destroy]

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path(@cocktail)
    else
      render :new
    end
  end

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    @cocktail.save
    redirect_to cocktails_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path(@cocktail)
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def index
    @doses = Dose.all
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

   def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<h1>Edit my cocktail</h1>

app/views/cocktails/index.html.erb
  <div class="navbar">
    <span>=</span>
      <span><em>Mister Cocktail</em></span>
    <span ><%= link_to " + cocktail", new_cocktail_path, class: "btn btn-primary"%></span>
  </div>

  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1531002329786-97e3efcb754b?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=5cc826864e1890cc916a71b4de444385&auto=format&fit=crop&w=750&q=80');">
  </div>


  <div class="container">
    <div class="cards" style="padding-top: 500px;">

    <% @cocktails.each do |cocktail| %>
    <!-- <div class="col-sm" -->
      <% if cocktail.photo.present? %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path cocktail.photo, crop: :fill %>');">
        <% else %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1517093911940-08cb5b3952e7?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=101c26932078be8b5fc48798d5b3f710&auto=format&fit=crop&w=1366&q=80');">
          <% end %>
        <div class="card-category">Popular</div>
          <div class="card-description">
            <h2><%= cocktail.name %></h2>
              <p><%= link_to "Delete", destroy_path(cocktail),
              method: :delete,
              data: { confirm: "Are you sure?" } %></p>
          </div>
         <%=  link_to "infos", cocktail_path(cocktail), :class=>"card-link" %>
      <!-- </div> -->
        </div>
      <% end %>
    </div>
  </div>

app/views/cocktails/new.html.erb
<h1>Cocktail#new</h1>
<p>Find me in app/views/cocktail/new.html.erb</p>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "add a cocktail", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/show.html.erb
<div class="show", style="margin-top: 70px">
<div class="navbar-show">
  <span><%= link_to "back", cocktails_path%></span>
    <span><em>Mister Cocktail</em></span>
  <span class="btn btn-primary"><%= link_to "+ dose", new_cocktail_dose_path(@cocktail) %></span>
</div>
<div class="cocktail-container">
  <div class="image" style="height: 400px; width:250">
    <%= cl_image_tag @cocktail.photo , height: 300, width: 400, crop: :fill if @cocktail.photo.present? %>
  </div>
  <div class="description">
      <%= @cocktail.name %>
        <% @cocktail.doses.each do |dose| %>
          <li>
            <%= dose.ingredient.name %>
            <%= dose.description %>
            <%= link_to "Delete", dose_destroy_path(dose),
              method: :delete,
              data: { confirm: "Are you sure?" } %>
          </li>
        <% end %>
    </div>
</div>
</div>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit "add a cocktail", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="yield">
    <%= yield %>
    </div>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>
  </body>
</html>